"""Regenerate the readable Markdown manuscript mirror from the LaTeX source.

The Springer Nature LaTeX file is authoritative.  This mechanical conversion
keeps the repository's secondary Markdown manuscript synchronized for search,
review and semantic-diff checks; it does not alter scientific content.
"""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "manuscript" / "latex" / "main.tex"
OUTPUT = ROOT / "manuscript" / "main" / "draft.md"


def unwrap(text: str, command: str, wrapper: str = "") -> str:
    pattern = re.compile(rf"\\{command}\{{([^{{}}]*)\}}")
    previous = None
    while previous != text:
        previous = text
        text = pattern.sub(lambda match: f"{wrapper}{match.group(1)}{wrapper}", text)
    return text


def main() -> None:
    source = SOURCE.read_text(encoding="utf-8")
    title = re.search(r"\\title\[[^]]*\]\{([^{}]+)\}", source).group(1)
    abstract = re.search(r"\\abstract\{(.*?)\}\n\n\\keywords", source, re.S).group(1)
    body = source[source.index(r"\section{Introduction}") : source.index(r"\bibliography")]

    body = re.sub(r"(?m)^%.*$", "", body)
    body = re.sub(r"\\section\*?\{([^{}]+)\}", r"\n## \1\n", body)
    body = re.sub(r"\\subsection\{([^{}]+)\}", r"\n### \1\n", body)
    body = re.sub(r"\\subsubsection\{([^{}]+)\}", r"\n#### \1\n", body)
    body = re.sub(r"\\begin\{(?:theorem|proposition)\}(?:\[([^]]+)\])?", r"\n**Formal statement: \1.**", body)
    body = re.sub(r"\\end\{(?:theorem|proposition)\}", "", body)
    body = re.sub(r"\\caption\{", "\n**Caption.** ", body)
    body = re.sub(r"\\includegraphics(?:\[[^]]*\])?\{([^{}]+)\}", r"[Figure: \1]", body)
    body = re.sub(r"\\(?:citep|citet|citealp)(?:\[[^]]*\])?\{[^{}]*\}", "", body)
    body = re.sub(r"\\(?:label|setcounter)(?:\[[^]]*\])?\{[^{}]*\}", "", body)
    body = re.sub(r"\\ref\{[^{}]*\}", "the referenced section", body)
    body = re.sub(r"\\begin\{[^{}]+\}|\\end\{[^{}]+\}", "", body)
    for command, wrapper in (
        ("textbf", "**"), ("emph", "*"), ("texttt", "`"),
        ("path", "`"), ("url", ""), ("mathrm", ""),
        ("operatorname", ""), ("text", ""),
    ):
        body = unwrap(body, command, wrapper)
    body = re.sub(r"\\(?:noindent|centering|small|footnotesize|scriptsize|toprule|midrule|bottomrule|backmatter)\b", "", body)
    body = re.sub(r"\\(?:setlength|fontsize|hypersetup|graphicspath)\{[^{}]*\}(?:\{[^{}]*\})?", "", body)
    body = body.replace(r"\%", "%").replace(r"\_", "_").replace(r"\&", "and")
    body = body.replace("---", "--")
    body = re.sub(r"(?m)^\\.*(?:tabular|minipage|linewidth|hfill|FloatBarrier|clearpage).*$", "", body)
    body = re.sub(r"\n{3,}", "\n\n", body).strip()

    output = (
        f"# {title}\n\n"
        "<!-- Auto-generated by scripts/sync_markdown_draft.py; main.tex is authoritative. -->\n\n"
        f"## Abstract\n\n{abstract}\n\n{body}\n"
    )
    OUTPUT.write_text(output, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
